import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Button from "@mui/material/Button";
import { Instagram } from "@mui/icons-material";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-auto min-h-screen relative">
        <div className="pb-[72px]">
          <Header />
          <div className="px-40 my-6">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
