import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./lib/providers";
import App from "@/components/App";

export const metadata: Metadata = {
  title: "Shopping App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className="mx-auto min-h-screen relative">
          <App children={children} />
        </body>
      </Providers>
    </html>
  );
}
